# Generated by Django 6.0.3 on 2026-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewcomment",
            name="source",
            field=models.CharField(
                choices=[("parser", "Parser"), ("llm", "LLM")],
                default="parser",
                max_length=20,
            ),
        ),
    ]
